<a href="https://colab.research.google.com/github/cinngyang/Python/blob/master/SampleCode/Python%E8%B3%87%E6%96%99%E7%B5%90%E6%A7%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 基本結構

+ 三元表達式 val= true_expr if condition else false-expr
+ tuple , tub=4,5,(2,3,5) , 長度不可變 , bisert 模組
+ List , lis=[1,112,345 ] , in , not   , 結合用 extend
+ dict , dic={key:value} 結合用 update
+ Set , 集合 , 透過 set 函數或中括號 set()
+ Function
  + enumerate
  + sorted / Reversed
  + zip / unzip , 不對稱 , 最短 , zip 序列元數配對
+ comprehension 
  + expr for val in collection if condition
  + key-expr : val-expr for val in collection
  


# tub and list
+ 逗號分隔, 長度不可變更

In [0]:
tub=2,3,5,'xyz',(8,9,10)
tub[3]
lis=[1,112,345 ]
lis.append(3)

In [2]:
lis_1=['a','b','c','d']
list_a=['e','f','g']
lis_2=[5,8,9,10,11,24,15]
lis_1.extend(list_a)
lis_1

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [3]:
dic={}
for i,(key,val) in enumerate(zip(lis_1,lis_2)):
  dic[key]=val
dic

{'a': 5, 'b': 8, 'c': 9, 'd': 10, 'e': 11, 'f': 24, 'g': 15}

In [4]:
pic=zip(lis_1,lis_2)
pic=list(pic)
fir,las=zip(*pic)
fir

('a', 'b', 'c', 'd', 'e', 'f', 'g')

# dict
+ 巢狀 dict

# Function
+ 位置參數 & 關鍵字
+ Lambda 

In [0]:
def my_func(x,y,z=1.5):
  if z > 1 :
    return z * (x+y)
  else :
    return z/(x+y)

In [0]:
def short_func(x):
  return x*2

eqiv_anon=lambda x:x*2

# Set
+ a.update(b) 聯集
+ a.union(b) a l b
+ a.symetric_difference(b)   

# NumPy
+ array[dim] , array[raw,column] , array[dim][column]  
+ arr3d[0,:1,:1]
+ 布林索引
+ narray 同質多維度陣列,未指定通常為 float 
+ shape & dtype(資料型態) & ndim
+ 建立特殊矩陣 zeros & ones & empty & identity
+ 建立可利用 np.aray(list)
+ narray 計算不使用 for 迴圈,(向量化), 兩各陣列比較(>,<,=)回傳布林陣列
+ 

In [0]:
import numpy as np

In [8]:
# 布林索引
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print('names.shape={0}'.format(names.shape))
print('data.shape={0}'.format(data.shape))
print("names=='Bob'",names=='Bob')
print(data)
data[names=='Bob']

names.shape=(7,)
data.shape=(7, 4)
names=='Bob' [ True False False  True False False False]
[[ 0.43166374  0.47274403  0.89556221  0.36720436]
 [ 0.5646024  -1.54909441 -1.43911049  0.65671743]
 [-0.33610698 -0.25869782 -1.02355327  0.61197521]
 [ 0.04804604 -1.60084154  3.24492346 -0.85285539]
 [ 0.80826505  0.01591996 -0.32408463  0.74357134]
 [ 2.74346985  0.45990001 -0.95156137 -1.36543539]
 [-1.20594548 -0.01195983 -0.10593772  0.20026469]]


array([[ 0.43166374,  0.47274403,  0.89556221,  0.36720436],
       [ 0.04804604, -1.60084154,  3.24492346, -0.85285539]])

In [9]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("ndim={0}".format(arr3d.ndim))
print("aray shape={0}".format(arr3d.shape))
print(arr3d)
print("arr3d[0]={0}".format(arr3d[0]))

ndim=3
aray shape=(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
arr3d[0]=[[1 2 3]
 [4 5 6]]


In [10]:
print("arr3d={0}".format(arr3d[0,:1,:2]))

arr3d=[[1 2]]


In [11]:
arr1=np.array([[1,2,3,],[4,5,6]])
arr2=np.array([[0,4,1],[4,5,7]])
arr2 > arr1

array([[False,  True, False],
       [False, False,  True]])

# Pandas - Series
+ 資料結構 series & DataFrame
+ Series 結構 data & Index , 建立 list 或 dict , 操作向 narray 
+ index 屬性 values , index , index 有 name 屬性
+ 以 dict 建立 index 為自動 join 缺值補 NaN 
+ Series 布林運算

In [12]:
import pandas as pd
obj=pd.Series([4,7,-5,3])
print('obj.index={0}',obj.index)
obj=pd.Series([4,7,-5,3],index=['d','b','a','c'])
stata={'ohio':3500,'Texas':71000,'Oregon':16000,'Utah':5000}
states=['Calofornia','ohio','Oregon','Texax']
obj3=pd.Series(stata)
obj4=pd.Series(stata,states)

obj.index={0} RangeIndex(start=0, stop=4, step=1)


In [13]:
print('obj.value={0}',obj.values)
print('obj.index={0}',obj.index)
print('obj3.value={0}',obj3.values)
print('obj3.index={0}',obj3.index)   
print('states=',states)
print('data & index 有差異{0},obj4= {1}'.format('\n',obj4))

obj.value={0} [ 4  7 -5  3]
obj.index={0} Index(['d', 'b', 'a', 'c'], dtype='object')
obj3.value={0} [16000 71000  5000  3500]
obj3.index={0} Index(['Oregon', 'Texas', 'Utah', 'ohio'], dtype='object')
states= ['Calofornia', 'ohio', 'Oregon', 'Texax']
data & index 有差異
,obj4= Calofornia        NaN
ohio           3500.0
Oregon        16000.0
Texax             NaN
dtype: float64


In [14]:
obj4.name='population'
obj4.index.name='state'
obj4

state
Calofornia        NaN
ohio           3500.0
Oregon        16000.0
Texax             NaN
Name: population, dtype: float64

# # Pandas - DataFrame
+ 每個欄位可以有不同的資料型態
+ 有列跟欄的 Index
+ 想像成 裝了很多 Series 物件的 dict , 每個 Series 使用同樣的 index
+ 建立方式 seriers , dict 
+ 取用欄 frame.columns or frame['colName']
+ 取用列 frame.loc['index'] (軸) frame.iloc[row,colunms] , iloc[-1]
+ 使用 Series 指定給欄時, index 會自動齊(join),為匹配填 NaN
+ 刪除欄 del frame['colName']
+ 轉置 frame.T

In [15]:
data={'state':['ohio','ohio','ohio','Nevada','Nevada','Nevada'],
      'year':[2000,2001,2002,2000,2001,2002],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
frame

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  Nevada  2000
4  2.9  Nevada  2001
5  3.2  Nevada  2002

In [16]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])
frame2.year

one      2000
two      2001
three    2002
four     2000
five     2001
six      2002
Name: year, dtype: int64

# 巢狀 dict 建立 Data Frame 
+ 外層 Key -> columns Index , 內層 Key row Index


In [17]:
pop={'Nevada':{2001:2.4,2002:2.9},
     'ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3=pd.DataFrame(pop)
frame3

Nevada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [18]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
ohio     1.5   1.7   3.6

# DataFrame - Index 物件
+ Pandas Inde 和 Set 不同, 他可以以重複標籤
+ index 屬性方法 P151 , append . defference , inrersection
+ 重作Row 索引 frame.reIndex(['inx1','inx2',...]) , columns 利用 frame.reIndex(columns=['inx1','inx2',...])  , method 可做計算補值
+ 搭配 loc 重作索引
+ 指定軸刪除 row 資料 frame.drop(['row idx','row idx']) 
+ 指定軸刪除 columns 資料 frame.drop(['col idx','col idx'] , axis='columns') 
+ 索引選擇與過濾
+ frame.loc[row,colunms , frame.iloc[-1:2] , 整數索引避免誤判
+ 算術運算 配對 index 沒有重複等同 outer join]
+ 算術運算 index null 填值 df.add(df2,fill_val=0)
+ DataFrame 與 Series 做運算 , 會每 row , col 運算 廣播(broadcast)
+ frame.sub(series,axis='idex') 對欄做運算

In [19]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
print('index[1:]=',index[1:])
'b' in  index

index[1:]= Index(['b', 'c'], dtype='object')


True

In [20]:
data=pd.DataFrame(np.arange(16).reshape(4,4),
                  index=['ohio','Colorado','Utah','New York'],
                  columns=['one','two','three','four'])
print(data)
data.drop(['Colorado','ohio'])

          one  two  three  four
ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

# DataFrame 運算
+ numpy 的全域函數可使用 np.abs(frame)
+ apply  , frame.apply(f) 逐欄運算 , apply(f,axis='columns') 逐列運算
+ applymp 對原素運算
+ frame.sort_index(axis=1,ascending=False)
+ frame.sort_value(by='column') , 

In [21]:
frame=pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
series=frame.iloc[0] # row 
print('frame','\r\n',frame)
print('series','\r\n',series)
print('frame-series','\r\n',frame-series)

frame 
           b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
series 
 b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64
frame-series 
           b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0


In [22]:
f=lambda x:x.max()-x.min()
print('frame','\r\n',frame)
frame.apply(f) # 每一欄算一次 

frame 
           b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


b    9.0
d    9.0
e    9.0
dtype: float64

In [23]:
frame.apply(f,axis='columns') #逐列呼叫

Utah      2.0
Ohio      2.0
Texas     2.0
Oregon    2.0
dtype: float64

In [24]:
def f(x):
  return pd.Series([x.min(),x.max()],index=['min','max'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [25]:
frame.apply(f)

b     d     e
min  0.0   1.0   2.0
max  9.0  10.0  11.0

# DataFrame - 切片
+ frame.loc[frame.columns=='Value']
+ frame.iloc[raw:col]